const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx={UMLCommands:require('../frontend/js/uml-commands.js')};vm.createContext(ctx);
const source=fs.readFileSync('frontend/js/local-ai.js','utf8');
vm.runInContext(source.slice(source.indexOf('function supplementPhotoDraft'),source.indexOf('function aiStatus')),ctx);
const original='Usuario\n+nombre\n+guardar()\n\nCuenta\n+saldo';
const result=ctx.supplementPhotoDraft(original,'Agrega atributo correo de tipo texto a clase Usuario');
assert.equal(result,'Usuario\n+nombre\ncorreo: String\n+guardar()\n\nCuenta\n+saldo');
assert.throws(()=>ctx.supplementPhotoDraft(original,'Agrega atributo correo de tipo texto a clase Otra'));
assert.throws(()=>ctx.supplementPhotoDraft(original,'Agrega atributo nombre de tipo texto a clase Usuario'));
assert.throws(()=>ctx.supplementPhotoDraft(original,'Crea clase Usuario'));
const added=ctx.supplementPhotoDraft(original,'Crea clase Producto con atributos precio de tipo entero');
assert(added.startsWith(original+'\n\nProducto\n'));
assert.equal(original,'Usuario\n+nombre\n+guardar()\n\nCuenta\n+saldo');
console.log('Photo plus voice: correct class targeted, methods preserved, separate class blocks, invalid additions rejected.');
const draft='Usuario\n+coreo: String\n-edad: Integer\n+guardar()\n\nCuenta\n+coreo: String';
assert.equal(ctx.supplementPhotoDraft(draft,'En la clase Usuario cambia el atributo coreo por correo.'),draft.replace('+coreo: String','+correo: String'));
assert.throws(()=>ctx.supplementPhotoDraft(draft,'En la clase Usuario cambia el atributo coreo por edad'));
assert.throws(()=>ctx.supplementPhotoDraft(draft,'En la clase Otra cambia el atributo coreo por correo'));
assert.throws(()=>ctx.supplementPhotoDraft(draft,'En la clase Usuario cambia el atributo guardar por correo'));
assert.throws(()=>ctx.supplementPhotoDraft(draft,'En la clase Usuario cambia el atributo inexistente por correo'));
console.log('Photo corrections preserve visibility/types and reject missing or colliding attributes.');
