const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let saves=0,closed=0,sent=0,badge='';
const ctx={state:{model:{toJSON:()=>({classes:[{id:'a',name:'Changed'}]})},ws:{readyState:1,send(){sent++},close(){closed++}}},collaborationState:{ready:false,base:{classes:[]},revision:1,inflight:null,conflict:null,role:'editor'},persistCollaboration(){saves++},copyDiagram:x=>JSON.parse(JSON.stringify(x)),sameDiagram:(a,b)=>JSON.stringify(a)===JSON.stringify(b),WebSocket:{OPEN:1},syncBadge:x=>badge=x};
vm.createContext(ctx);const src=fs.readFileSync('frontend/js/collaboration.js','utf8');vm.runInContext(src.slice(src.indexOf('function offlineSyncMessage()'),src.indexOf('function refreshSyncBadge(')),ctx);vm.runInContext(src.slice(src.indexOf('function broadcastChange()'),src.indexOf('async function initWebSocket()')),ctx);
vm.runInContext('broadcastChange()',ctx);assert.equal(saves,1);assert.equal(sent,0);
ctx.collaborationState.ready=true;ctx.collaborationState.conflict={};vm.runInContext('broadcastChange()',ctx);assert.equal(saves,2);assert.equal(sent,0);
ctx.collaborationState.conflict=null;ctx.state.ws.send=()=>{throw Error('closed during send')};vm.runInContext('broadcastChange()',ctx);assert.equal(ctx.collaborationState.inflight,null);assert.equal(closed,1);assert.equal(saves,3);
ctx.state.ws.send=()=>sent++;vm.runInContext('broadcastChange()',ctx);assert.equal(sent,1);assert(ctx.collaborationState.inflight);
ctx.state.isRemoteUpdate=true;vm.runInContext('broadcastChange()',ctx);assert.equal(saves,4);
console.log('Offline edits persist before readiness and during conflicts; failed sends release in-flight state.');
vm.runInContext(src.slice(src.indexOf('function refreshSyncBadge('),src.indexOf('function persistCollaboration()')),ctx);
vm.runInContext('refreshSyncBadge(2)',ctx);assert.equal(badge,'Guardando cambios…');
ctx.collaborationState.inflight=null;
vm.runInContext('refreshSyncBadge()',ctx);assert.equal(badge,'Cambios pendientes de sincronizar');
ctx.collaborationState.base=ctx.state.model.toJSON();
vm.runInContext('refreshSyncBadge()',ctx);assert.equal(badge,'Sincronizado');
ctx.collaborationState.conflict={};
vm.runInContext('refreshSyncBadge(3)',ctx);assert.equal(badge,'Conflicto: revisa tus cambios');
console.log('Presence and acknowledgments cannot hide pending changes or conflicts.');
const storage=new Map();ctx.state.projectId='test';
ctx.localStorage={getItem:key=>storage.get(key)||null};ctx.collaborationStorageKey=()=> 'current';
vm.runInContext(src.slice(src.indexOf('function savedCollaboration()'),src.indexOf('const collaborationState =')),ctx);
storage.set('current','broken JSON');storage.set('collaboration_latest_test','backup');
storage.set('backup',JSON.stringify({diagram:{classes:[{id:'saved'}]},revision:2}));
assert.equal(vm.runInContext('savedCollaboration().diagram.classes[0].id',ctx),'saved');
assert.equal(storage.get('current'),'broken JSON');
storage.set('backup','{}');assert.equal(vm.runInContext('savedCollaboration()',ctx),null);
console.log('Damaged drafts fall back to a valid backup without deleting the original.');
ctx.saveCurrentProjectToStorage=()=>{};
ctx.localStorage.setItem=()=>{throw Error('quota exceeded')};
vm.runInContext(src.slice(src.indexOf('function persistCollaboration()'),src.indexOf('function applySharedDiagram(')),ctx);
vm.runInContext('persistCollaboration(); refreshSyncBadge()',ctx);
assert.equal(ctx.collaborationState.localSaveFailed,true);
assert(badge.includes('No se pudo guardar'));
assert(vm.runInContext('offlineSyncMessage()',ctx).includes('no se pudo guardar'));
ctx.localStorage.setItem=(key,value)=>storage.set(key,value);
vm.runInContext('persistCollaboration()',ctx);
assert.equal(ctx.collaborationState.localSaveFailed,false);
console.log('Storage failure stays visible and successful persistence clears the warning.');
